🩹 ensure GITHUB_TOKEN variable is defined

diff --git a/.github/workflows/reusable_workflow.yml b/.github/workflows/reusable_workflow.yml
--- a/.github/workflows/reusable_workflow.yml
+++ b/.github/workflows/reusable_workflow.yml
@@ -106,6 +106,7 @@ jobs:
 
       - name: Run Tests
         env:
+          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GA }}
           ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
           SRID: ${{ secrets.SRID }}
         run: |
@@ -128,6 +129,10 @@ jobs:
           export OPENERP_IGNORE_PUBSUB=1
           cd ${{github.workspace}}
           export GIT_TERMINAL_PROMPT=0
+
+          git config --global --get-regexp '^url\..*\.insteadof$' || true
+          git config --global --show-origin --get-regexp '^url\..*\.insteadof$' || true
+          test -n "${GITHUB_TOKEN:-}" && echo "GITHUB_TOKEN is set" || echo "GITHUB_TOKEN is missing"
 
           git config --global \
             url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf \
